import type { Config } from 'tailwindcss';

const config = {
	darkMode: ['class'],
	content: [
		'./pages/**/*.{ts,tsx}',
		'./components/**/*.{ts,tsx}',
		'./app/**/*.{ts,tsx}',
		'./src/**/*.{ts,tsx}',
		'./sections/**/*.{ts,tsx}',
		'*.{js,ts,jsx,tsx,mdx}',
	],
	prefix: '',
	theme: {
		container: {
			center: true,
			padding: '2rem',
			screens: {
				'2xl': '1400px',
			},
		},
		extend: {
			fontFamily: {
				sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
				display: ['var(--font-jakarta)', 'system-ui', 'sans-serif'],
			},
			colors: {
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				primary: {
					DEFAULT: 'hsl(var(--primary))',
					foreground: 'hsl(var(--primary-foreground))',
					50: 'var(--color-primary-50)',
					100: 'var(--color-primary-100)',
					200: 'var(--color-primary-200)',
					300: 'var(--color-primary-300)',
					400: 'var(--color-primary-400)',
					500: 'var(--color-primary-500)',
					600: 'var(--color-primary-600)',
					700: 'var(--color-primary-700)',
					800: 'var(--color-primary-800)',
					900: 'var(--color-primary-900)',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				// Modern color palette
				modern: {
					blue: {
						50: '#eff6ff',
						100: '#dbeafe',
						200: '#bfdbfe',
						300: '#93c5fd',
						400: '#60a5fa',
						500: '#3b82f6',
						600: '#2563eb',
						700: '#1d4ed8',
						800: '#1e40af',
						900: '#1e3a8a',
					},
					purple: {
						50: '#faf5ff',
						100: '#f3e8ff',
						200: '#e9d5ff',
						300: '#d8b4fe',
						400: '#c084fc',
						500: '#a855f7',
						600: '#9333ea',
						700: '#7c3aed',
						800: '#6b21a8',
						900: '#581c87',
					},
					indigo: {
						50: '#eef2ff',
						100: '#e0e7ff',
						200: '#c7d2fe',
						300: '#a5b4fc',
						400: '#818cf8',
						500: '#6366f1',
						600: '#4f46e5',
						700: '#4338ca',
						800: '#3730a3',
						900: '#312e81',
					},
				},
				primaryColor: {
					50: 'var(--primaryColor-50)',
					100: 'var(--primaryColor-100)',
					200: 'var(--primaryColor-200)',
					300: 'var(--primaryColor-300)',
					400: 'var(--primaryColor-400)',
					500: 'var(--primaryColor-500)',
					600: 'var(--primaryColor-600)',
					700: 'var(--primaryColor-700)',
					800: 'var(--primaryColor-800)',
					900: 'var(--primaryColor-900)',
				},

				secondaryColor: {
					50: 'var(--secondaryColor-50)',
					100: 'var(--secondaryColor-100)',
					200: 'var(--secondaryColor-200)',
					300: 'var(--secondaryColor-300)',
					400: 'var(--secondaryColor-400)',
					500: 'var(--secondaryColor-500)',
					600: 'var(--secondaryColor-600)',
					700: 'var(--secondaryColor-700)',
					800: 'var(--secondaryColor-800)',
					900: 'var(--secondaryColor-900)',
				},
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
				'2xl': '1rem',
				'3xl': '1.5rem',
			},
			keyframes: {
				'accordion-down': {
					from: { height: '0' },
					to: { height: 'var(--radix-accordion-content-height)' },
				},
				'accordion-up': {
					from: { height: 'var(--radix-accordion-content-height)' },
					to: { height: '0' },
				},
				'slide-up': {
					from: { opacity: '0', transform: 'translateY(20px)' },
					to: { opacity: '1', transform: 'translateY(0)' },
				},
				'fade-in': {
					from: { opacity: '0' },
					to: { opacity: '1' },
				},
				'scale-in': {
					from: { opacity: '0', transform: 'scale(0.9)' },
					to: { opacity: '1', transform: 'scale(1)' },
				},
				shimmer: {
					'0%': { backgroundPosition: '-200% 0' },
					'100%': { backgroundPosition: '200% 0' },
				},
				'bounce-gentle': {
					'0%, 100%': { transform: 'translateY(0)' },
					'50%': { transform: 'translateY(-10px)' },
				},
				'pulse-slow': {
					'0%, 100%': { opacity: '1' },
					'50%': { opacity: '0.5' },
				},
				'gradient-shift': {
					'0%': { backgroundPosition: '0% 50%' },
					'50%': { backgroundPosition: '100% 50%' },
					'100%': { backgroundPosition: '0% 50%' },
				},
				float: {
					'0%, 100%': { transform: 'translateY(0px)' },
					'50%': { transform: 'translateY(-20px)' },
				},
				'slide-in-left': {
					from: { opacity: '0', transform: 'translateX(-20px)' },
					to: { opacity: '1', transform: 'translateX(0)' },
				},
				'slide-in-right': {
					from: { opacity: '0', transform: 'translateX(20px)' },
					to: { opacity: '1', transform: 'translateX(0)' },
				},
				'zoom-in': {
					from: { opacity: '0', transform: 'scale(0.8)' },
					to: { opacity: '1', transform: 'scale(1)' },
				},
				'rotate-in': {
					from: { opacity: '0', transform: 'rotate(-180deg) scale(0.8)' },
					to: { opacity: '1', transform: 'rotate(0deg) scale(1)' },
				},
			},
			animation: {
				'accordion-down': 'accordion-down 0.2s ease-out',
				'accordion-up': 'accordion-up 0.2s ease-out',
				'slide-up': 'slide-up 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
				'fade-in': 'fade-in 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
				'scale-in': 'scale-in 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
				shimmer: 'shimmer 1.5s infinite',
				'bounce-gentle': 'bounce-gentle 2s ease-in-out infinite',
				'pulse-slow': 'pulse-slow 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
				'gradient-shift': 'gradient-shift 3s ease infinite',
				float: 'float 6s ease-in-out infinite',
				'slide-in-left': 'slide-in-left 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
				'slide-in-right': 'slide-in-right 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
				'zoom-in': 'zoom-in 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
				'rotate-in': 'rotate-in 0.4s cubic-bezier(0.4, 0, 0.2, 1)',
			},
			spacing: {
				'18': '4.5rem',
				'88': '22rem',
				'128': '32rem',
				'144': '36rem',
			},
			maxWidth: {
				'8xl': '88rem',
				'9xl': '96rem',
			},
			backdropBlur: {
				xs: '2px',
			},
			boxShadow: {
				soft: '0 2px 15px -3px rgba(0, 0, 0, 0.07), 0 10px 20px -2px rgba(0, 0, 0, 0.04)',
				'soft-lg': '0 10px 25px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
				modern: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)',
				'modern-lg': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
				glass: '0 8px 32px 0 rgba(31, 38, 135, 0.37)',
				glow: '0 0 20px rgba(59, 130, 246, 0.3)',
				'glow-lg': '0 0 40px rgba(59, 130, 246, 0.4)',
			},
			backgroundImage: {
				'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
				'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
				'gradient-primary': 'var(--gradient-primary)',
				'gradient-secondary': 'var(--gradient-secondary)',
				'gradient-accent': 'var(--gradient-accent)',
				'gradient-success': 'var(--gradient-success)',
				'gradient-warning': 'var(--gradient-warning)',
				'gradient-danger': 'var(--gradient-danger)',
			},
			backgroundSize: {
				'200%': '200%',
			},
			backgroundPosition: {
				'center-center': 'center center',
			},
			transitionProperty: {
				all: 'all',
				colors: 'color, background-color, border-color, text-decoration-color, fill, stroke',
				opacity: 'opacity',
				shadow: 'box-shadow',
				transform: 'transform',
			},
			transitionTimingFunction: {
				'bounce-in': 'cubic-bezier(0.68, -0.55, 0.265, 1.55)',
				smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
				'ease-out': 'cubic-bezier(0, 0, 0.2, 1)',
				'ease-in': 'cubic-bezier(0.4, 0, 1, 1)',
			},
			transitionDuration: {
				'400': '400ms',
				'500': '500ms',
				'600': '600ms',
				'700': '700ms',
				'800': '800ms',
				'900': '900ms',
				'1000': '1000ms',
			},
			zIndex: {
				'60': '60',
				'70': '70',
				'80': '80',
				'90': '90',
				'100': '100',
			},
			scale: {
				'102': '1.02',
				'103': '1.03',
				'104': '1.04',
				'105': '1.05',
			},
			rotate: {
				'1': '1deg',
				'2': '2deg',
				'3': '3deg',
				'6': '6deg',
				'12': '12deg',
				'15': '15deg',
				'30': '30deg',
				'60': '60deg',
				'90': '90deg',
				'180': '180deg',
			},
			skew: {
				'1': '1deg',
				'2': '2deg',
				'3': '3deg',
				'6': '6deg',
				'12': '12deg',
			},
		},
	},
	plugins: [require('tailwindcss-animate'), require('@tailwindcss/forms'), require('tailwind-scrollbar-hide')],
} satisfies Config;

export default config;
